language: python

python:
  - 2.7

services:
  - docker

install:
  - docker run --name mindbender-mongo -d mongo
  - docker build -t mindbender/core -f Dockerfile-maya2016 .

script:
  # Run Tests
  - >
    docker run
    --rm
    -v $(pwd):/workspace
    --link mindbender-mongo:mongo
    -e COVERALLS_REPO_TOKEN
    -e TRAVIS_JOB_ID
    -e MINDBENDER_MONGO=mongodb://mongo:27017
    mindbender/core

  # Build Documentation
  - >
    docker run
    --rm
    -v $(pwd):/workspace
    --entrypoint=mayapy
    mindbender/core
    -m sphinx docs/source docs/build

before_deploy:
  - chmod -R 777 docs/build/
  - cd docs/build
  - ls -l

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
