language: python

sudo: required
dist: trusty

python:
  - 2.7

services:
  - docker

install:
  - pip install coveralls
  - docker build -t pyblish/mindbender -f Dockerfile-maya2016 .

script:
  - docker run --rm -v $(pwd):/workspace pyblish/mindbender

after_success:
  - coveralls
