language: python

sudo: required
dist: trusty

python:
  - 2.7

services:
  - docker

install:
  - docker run --name mindbender-mongo -d mongo
  - docker build -t pyblish/mindbender -f Dockerfile-maya2016 .

script:
  - >
    docker run
    --rm
    -v $(pwd):/workspace
    --link mindbender-mongo:mongo
    -e COVERALLS_REPO_TOKEN
    -e TRAVIS_JOB_ID
    -e MINDBENDER_MONGO=mongodb://mongo:27017
    pyblish/mindbender

after_script:
  - >
    docker run
    --rm
    -v $(pwd):/workspace
    --link mindbender-mongo:mongo
    -e COVERALLS_REPO_TOKEN
    -e TRAVIS_JOB_ID
    -e MINDBENDER_MONGO=mongodb://mongo:27017
    --entrypoint="sphinx-build docs/source docs/build"
    pyblish/mindbender

before_deploy:
  - cd docs/build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
